CREATE TABLE IF NOT EXISTS appointments (
id UUID NOT NULL,
date TIMESTAMP ,
complaints VARCHAR(255),
patient_id UUID,
doctor_id UUID,
PRIMARY KEY (id),
FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE ON UPDATE CASCADE);